### ISSUE TITLE
Form detalles de planes

### ISSUE THREAD

**Issue by Nidev-lab** [RollingTeam3/rolling_gym#10]
## Proceso

1. Ingrese a la pagina.
2. Quise hacer una consulta.

## Resultado esperado

• Que no se permita colocar numeros ni signos en el nombre del usuario.
• Que haya un limite de caracteres a colocar en el mensaje.
• Que no se muestre ningun mensaje por consola.

## Resultado actual

• Se permiten colocar numero y signos en el nombre.
• No se encuentra un max de caracteres a colocar en el mensaje.
• Se muestran mensajes por consola.

## Captura

![image](https://github.com/RollingTeam3/rolling_gym/assets/53904695/6648d2af-baa9-435d-9282-2652b87a058c)
![image](https://github.com/RollingTeam3/rolling_gym/assets/53904695/79547102-0a04-4c4b-b36c-ca38cf76ea16)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by LucasCorbalan3** [comment]
Resuelto en commit [08edcee682239f16657e1aeaa70b105c8170a756]
