### ISSUE TITLE
Seccion detalles de planes / Page not found

### ISSUE THREAD

**Issue by Nidev-lab** [RollingTeam3/rolling_gym#11]
## Proceso

1. Ingrese a la pagina.
2. Me loguee con un usuario.
3. Quise saber mas sobre un plan.

## Resultado esperado

• Que al ingresar a un plan para saber mas la pagina funcione correctamente.

## Resultado actual

• Al Ingresar los botones del nav dejan de funcionar y generan errores por consola.
• Al actualizar la pagina, la misma deja de funcionar.

## Captura

https://github.com/RollingTeam3/rolling_gym/assets/53904695/dbd49685-d081-4bd5-8e95-d254f851466e

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by LucasCorbalan3** [comment]
Resuelto en commit [af9e85527972c2043e26d93b3e8b3f44b36de237] [435fb4914eee7f6a42b4cd0400f5c6a0b3093aac]
