### ISSUE TITLE
Nombre y logo

### ISSUE THREAD

**Issue by Nidev-lab** [RollingTeam3/rolling_gym#9]
## Proceso

1. Ingrese a la pagina.

## Resultado esperado

• Encontrar nombre y logo de la pagina.

## Resultado actual

• No se encuentra nombre ni logo de la pagina.

## Captura

![image](https://github.com/RollingTeam3/rolling_gym/assets/53904695/37e5b49f-e04f-4903-b746-67d13fb236cc)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by LucasCorbalan3** [comment]
Resuelto en commit [584f93fa8e580a461719c4ccd44c92d115580060]
